# Generated by Django 5.0.1 on 2024-01-28 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomDepartement', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomFiliere', models.CharField(max_length=255)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etudient.departement')),
            ],
        ),
        migrations.CreateModel(
            name='Etudient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cne', models.CharField(max_length=30, unique=True)),
                ('cin', models.CharField(max_length=30, unique=True)),
                ('nomEtudientAr', models.CharField(blank=True, max_length=255, null=True)),
                ('prenomEtudientAr', models.CharField(blank=True, max_length=255, null=True)),
                ('adresse', models.TextField()),
                ('adresseAr', models.TextField(blank=True, null=True)),
                ('sexe', models.CharField(blank=True, max_length=20, null=True)),
                ('villeDeNaissance', models.CharField(max_length=255)),
                ('villeDeNaissanceAr', models.CharField(blank=True, max_length=255, null=True)),
                ('dateDeNaissance', models.DateField()),
                ('telEtudient', models.CharField(blank=True, max_length=30, null=True)),
                ('situation_familiale', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etudient.filiere')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomModule', models.CharField(max_length=255)),
                ('coefficient', models.FloatField()),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etudient.filiere')),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomMatiere', models.CharField(max_length=255)),
                ('coefficient', models.FloatField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etudient.module')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(max_length=255)),
                ('coefficient', models.FloatField()),
                ('annee', models.CharField(max_length=16)),
                ('etudient', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='etudient.etudient')),
            ],
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telProfesseur', models.CharField(blank=True, max_length=30, null=True)),
                ('cin', models.CharField(max_length=30, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Enseigner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='etudient.matiere')),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='etudient.professeur')),
            ],
        ),
    ]
