# Generated by Django 5.0.1 on 2024-01-29 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etudient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professeur',
            name='user',
        ),
        migrations.DeleteModel(
            name='Enseigner',
        ),
        migrations.DeleteModel(
            name='Professeur',
        ),
    ]
