# Generated by Django 5.0.1 on 2024-01-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudient', '0002_remove_professeur_user_delete_enseigner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='publier',
            field=models.BooleanField(default=False),
        ),
    ]
