# Generated by Django 5.0.1 on 2024-02-01 17:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudient', '0004_alter_matiere_coefficient'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='matiere',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='etudient.matiere'),
        ),
        migrations.AddField(
            model_name='note',
            name='note',
            field=models.FloatField(default='0.0', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(20.0)]),
        ),
        migrations.AlterField(
            model_name='module',
            name='coefficient',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='note',
            name='coefficient',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
