# Generated by Django 5.0.1 on 2024-02-01 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etudient', '0006_alter_matiere_coefficient_alter_module_coefficient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departement',
            old_name='nomDepartement',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='filiere',
            old_name='nomFiliere',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='matiere',
            old_name='nomMatiere',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='nomModule',
            new_name='nom',
        ),
    ]
